version: '3.8'
services:
  angular-app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    depends_on:
      - node
  
  node:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: npm install